### ISSUE TITLE
const experssion for `vecmem::static_array`

### ISSUE THREAD

**Issue by beomki-yeo** [acts-project/vecmem#107]
While integrating vecmem functionality into detray, I've found that vecmem::static_array doesn't support the const expression - is it intended or just missing it?

**Comment by paulgessinger** [comment]
Hmm, other than `fill`, I believe all other methods are at least marked `constexpr`. Where do you encounter problems with this?

**Comment by beomki-yeo** [comment]
One of the cases is at the mask types:

https://github.com/acts-project/detray/blob/b6426b91a663e923bf33056acbdfecebafe0aeb8/core/include/masks/annulus2.hpp#L70-L73

**Comment by krasznaa** [comment]
Hi Beomki,

Please be a lot more verbose. What is the exact issue that you're running into? What is the exact compiler error that you get?

We did not really test how well `vecmem::array` behaves as a `constexpr` object. (Which is what you seem to be doing there.) So yes, there could very well be things that we should improve. But we'd need a much more exact description of what is not working. Mainly because I myself do not have a lot of experience with writing classes that provide good `constexpr` behaviour.

Attila

**Comment by beomki-yeo** [comment]
Sorry for insufficient explanation.
Following is the compiler error message when I change the data type of `darray` from `std::array` to `vecmem::static_array` in https://github.com/acts-project/detray/blob/b6426b91a663e923bf33056acbdfecebafe0aeb8/plugins/algebra/include/detray/array/include/plugins/algebra/array_definitions.hpp#L11

```
/home/beomki/projects/detray/detray/core/include/masks/annulus2.hpp:70:37: error: the type ‘const mask_tolerance’ {aka ‘const vecmem::static_array<double, 2>’} of ‘constexpr’ variable ‘detray::annulus2<>::within_epsilon’ is not literal
     static constexpr mask_tolerance within_epsilon = {
                                     ^~~~~~~~~~~~~~
In file included from /home/beomki/projects/detray/detray/extern/algebra-plugins/core/common/include/algebra/common/types.hpp:17,
                 from /home/beomki/projects/detray/detray/extern/algebra-plugins/core/include/array/include/algebra/definitions/std_array.hpp:10,
                 from /home/beomki/projects/detray/detray/plugins/algebra/include/detray/array/include/plugins/algebra/array_definitions.hpp:2,
                 from /home/beomki/projects/detray/detray/tests/benchmarks/array/array_intersect_surfaces.cpp:8:
/home/beomki/projects/detray/detray_build/_deps/vecmem-src/core/include/vecmem/containers/static_array.hpp:33:7: note: ‘vecmem::static_array<double, 2>’ is not literal because:
 class static_array {
       ^~~~~~~~~~~~
/home/beomki/projects/detray/detray_build/_deps/vecmem-src/core/include/vecmem/containers/static_array.hpp:33:7: note:   ‘vecmem::static_array<double, 2>’ is not an aggregate, does not have a trivial default constructor, and has no ‘constexpr’ constructor that is not a copy or move constructor
In file included from /home/beomki/projects/detray/detray/core/include/masks/masks.hpp:8,
                 from /home/beomki/projects/detray/detray/tests/common/include/tests/common/benchmark_intersect_surfaces.inl:12,
                 from /home/beomki/projects/detray/detray/tests/benchmarks/array/array_intersect_surfaces.cpp:9:
/home/beomki/projects/detray/detray/core/include/masks/annulus2.hpp:70:37: error: in-class initialization of static data member ‘const mask_tolerance detray::annulus2<>::within_epsilon’ of non-literal type
```

Thus, it is from the non-literal type of vecmem::static_array but I don't know well what it really means

**Comment by stephenswat** [comment]
Closing this, since #111 has been merged.
