### ISSUE TITLE
Jagged vector buffer constructor of non-static size not using given sizes.

### ISSUE THREAD

**Issue by guilhermeAlmeida1** [acts-project/vecmem#219]
I stumbled upon this error by chance, as currently we have no using for creating non-static sized buffers starting with size different than 0, but it could come in handy in the future.
Right now the sizes of the created buffer are not initialised, only its capacities.
https://github.com/acts-project/vecmem/blob/971a7ef615a0f8cc8f063bbe3a95929dac438f84/core/include/vecmem/containers/impl/jagged_vector_buffer.ipp#L104-L145

**Comment by krasznaa** [comment]
Let's discuss in #95 instead.
