### ISSUE TITLE
Vectors do not support boolean template types

### ISSUE THREAD

**Issue by stephenswat** [acts-project/vecmem#236]
The standard library dictates that `std::vector<bool>` (and, by extension, `vecmem::vector`) is a specialization without a guaranteed `.data()` member function on which vecmem relies. This means booleans cannot be stored in vecmem vectors.

**Comment by stephenswat** [comment]
By the way this is not a "we should fix this" but rather a "we should document and add usable error messages".

**Comment by krasznaa** [comment]
Yeah, this is a fairly well-known corner-case of `std::vector`. (In the ATLAS EDM we have a hack around this, but I think that only caused us more problems over the years than how many issues it solved.)

I suppose we could add `static_assert`-s into the appropriate places against it. Of course creating `vecmem::vector<bool>` will never trigger an error, but at least the appropriate `vecmem::get_data` functions, `vecmem::data::vector_view<bool>`, etc. could throw an error. :thinking:
